### ISSUE TITLE
Multi-regional input data?

### ISSUE THREAD

**Issue by hdetering** [GuanLab/FastClone_GuanLab#2]
Hello,

I tried running FastClone with multiple samples and got this error:
```
$ fastclone load-pyclone R1 R1.tsv None load-pyclone R2 R2.tsv None load-pyclone R3 R3.tsv None load-pyclone R4 R4.tsv None load-pyclone R5 R5.tsv None load-pyclone R6 R6.tsv None load-pyclone R7 R7.tsv None load-pyclone R8 R8.tsv None solve ./result
[2020-10-18 14:01:44.588114] INFO: fastclone.__main__: Loading R1 ...
[2020-10-18 14:01:44.588250] INFO: fastclone.__main__: PyClone file R1.tsv
[2020-10-18 14:01:44.588299] INFO: fastclone.__main__: Infer the purity later.
[2020-10-18 14:01:44.668756] INFO: fastclone.__main__: Loading R2 ...
[2020-10-18 14:01:44.668871] INFO: fastclone.__main__: PyClone file R2.tsv
[2020-10-18 14:01:44.668925] INFO: fastclone.__main__: Infer the purity later.
[2020-10-18 14:01:44.675727] INFO: fastclone.__main__: Loading R3 ...
[2020-10-18 14:01:44.675838] INFO: fastclone.__main__: PyClone file R3.tsv
[2020-10-18 14:01:44.675885] INFO: fastclone.__main__: Infer the purity later.
[2020-10-18 14:01:44.682005] INFO: fastclone.__main__: Loading R4 ...
[2020-10-18 14:01:44.682076] INFO: fastclone.__main__: PyClone file R4.tsv
[2020-10-18 14:01:44.682122] INFO: fastclone.__main__: Infer the purity later.
[2020-10-18 14:01:44.687913] INFO: fastclone.__main__: Loading R5 ...
[2020-10-18 14:01:44.687989] INFO: fastclone.__main__: PyClone file R5.tsv
[2020-10-18 14:01:44.688037] INFO: fastclone.__main__: Infer the purity later.
[2020-10-18 14:01:44.693698] INFO: fastclone.__main__: Loading R6 ...
[2020-10-18 14:01:44.693767] INFO: fastclone.__main__: PyClone file R6.tsv
[2020-10-18 14:01:44.693813] INFO: fastclone.__main__: Infer the purity later.
[2020-10-18 14:01:44.699844] INFO: fastclone.__main__: Loading R7 ...
[2020-10-18 14:01:44.699927] INFO: fastclone.__main__: PyClone file R7.tsv
[2020-10-18 14:01:44.699977] INFO: fastclone.__main__: Infer the purity later.
[2020-10-18 14:01:44.705439] INFO: fastclone.__main__: Loading R8 ...
[2020-10-18 14:01:44.705505] INFO: fastclone.__main__: PyClone file R8.tsv
[2020-10-18 14:01:44.705555] INFO: fastclone.__main__: Infer the purity later.
Traceback (most recent call last):
  File "/mnt/netapp1/APPS/CommonCondaEnvironments/fastclone/bin/fastclone", line 8, in <module>
    sys.exit(main())
  File "/mnt/netapp1/APPS/CommonCondaEnvironments/fastclone/lib/python3.8/site-packages/fastclone/__main__.py", line 130, in main
    fire.Fire(Entrypoint)
  File "/mnt/netapp1/APPS/CommonCondaEnvironments/fastclone/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/mnt/netapp1/APPS/CommonCondaEnvironments/fastclone/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/mnt/netapp1/APPS/CommonCondaEnvironments/fastclone/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/netapp1/APPS/CommonCondaEnvironments/fastclone/lib/python3.8/site-packages/fastclone/__main__.py", line 112, in solve
    raise NotImplementedError('mult-sample inference is not available')
NotImplementedError: mult-sample inference is not available
```

So it seems that deconvolution of multi-regional data is not supported at this point.

Do you have plans to support this kind of data in the near future?

Cheers,
Harry

**Comment by Yaoyx** [comment]
Hi Harry,

Yea, currently, we haven't built any function for multi-regional inference yet, but I think it is very interesting. Just to clarify, do you mean using the different region samples of one tumor to reconstruct the entire tumor phylogeny?

And in case, if you wanna do multi-samples inference, the temporary solution is using bash to do a for-loop:

#!/bin/bash

filenames='ls ./DO*'
N=10
for sample_file in $filenames
do
        ((i=i%N)); ((i++==0)) && wait
        fastclone load-pyclone prop $sample_file None solve outputs/${sample_file}_output &
done
