### ISSUE TITLE
Missing dependency (ModuleNotFoundError: No module named 'matplotlib')

### ISSUE THREAD

**Issue by HenrikBengtsson** [GuanLab/FastClone_GuanLab#5]
# Issue

I installed FastClone in a fresh virtual environment following the (non-GitHub) installation instruction in the README.  However, I get:

```r
(FastClone) [henrik@centos7 FastClone]$ fastclone --help
Traceback (most recent call last):
  File "/c4/home/henrik/tests/FastClone/bin/fastclone", line 5, in <module>
    from fastclone.__main__ import main
  File "/c4/home/henrik/tests/FastClone/lib/python3.6/site-packages/fastclone/__init__.py", line 2, in <module>
    from .phylogeny import *
  File "/c4/home/henrik/tests/FastClone/lib/python3.6/site-packages/fastclone/phylogeny.py", line 5, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```

# Suggestion

Installing **matplotlib** manually solved the problem.  I'm not a Python expert but could it be that you've forgot to declare `matplotlib` as a dependency?

# Details

This is how I installed FastClone in a virtual environment running Python 3.6.8 on an up-to-date CentOS 7.9 environment.

```sh
[henrik@centos7 tests]$ virtualenv -p python3 FastClone
[henrik@centos7 FastClone]$ cd FastClone

(FastClone) [henrik@centos7 FastClone]$ python --version
Python 3.6.8

(FastClone) [henrik@centos7 FastClone]$ python -m pip install --upgrade pip

(FastClone) [henrik@centos7 FastClone]$ pip list
Package    Version
---------- -------
mpi4py     1.3.1
pip        21.0
setuptools 51.1.1
wheel      0.36.2

(FastClone) [henrik@centos7 FastClone]$ pip install fastclone-guanlab
...

(FastClone) [henrik@centos7 FastClone]$ pip list
Package           Version
----------------- -------
decorator         4.4.2
fastclone-guanlab 1.0.5
fire              0.4.0
joblib            1.0.0
Logbook           1.5.3
mpi4py            1.3.1
networkx          2.5
numpy             1.19.5
pandas            1.1.5
pip               21.0
python-dateutil   2.8.1
pytz              2020.5
scikit-learn      0.24.1
scipy             1.5.4
setuptools        51.1.1
six               1.15.0
termcolor         1.1.0
threadpoolctl     2.1.0
wheel             0.36.2

(FastClone) [henrik@centos7 FastClone]$ which fastclone
~/tests/FastClone/bin/fastclone

(FastClone) [henrik@centos7 FastClone]$ fastclone
Traceback (most recent call last):
  File "/c4/home/henrik/tests/FastClone/bin/fastclone", line 5, in <module>
    from fastclone.__main__ import main
  File "/c4/home/henrik/tests/FastClone/lib/python3.6/site-packages/fastclone/__init__.py", line 2, in <module>
    from .phylogeny import *
  File "/c4/home/henrik/tests/FastClone/lib/python3.6/site-packages/fastclone/phylogeny.py", line 5, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```

# Workaround

Manually install **matplotlib** as in:

```sh
(FastClone) [henrik@centos7 FastClone]$ pip install matplotlib
```

fixed the problem:

```sh
(FastClone) [henrik@centos7 FastClone]$ fastclone --help

NAME
    fastclone - FastClone: a tumour subclone inference tool

SYNOPSIS
    fastclone -

DESCRIPTION
    Check subcommands for sample loading.
    Chain multiple subcommands load multiple samples and infer.
    Use '-- --help' to show help messages.

...
```

**Comment by Yaoyx** [comment]
Thank you so much for your suggestion. The new dependency list has included "matplotlib" package now.

**Comment by HenrikBengtsson** [comment]
Great. Thxs
